apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-01
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
      path: /tmp
      type: Directory