apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: nginxdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: mypod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
