apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldeployments
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysqlpod
      labels:
        app: mysql

    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
          # Use secret in real usage
          - name: MYSQL_ROOT_PASSWORD
            value: password
          ports:
          - containerPort: 3306
            name: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mysqlservice


spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30002
