apiVersion: batch/v1
kind: Job
metadata:
  name: maths
  labels:
    app: mathsapp
spec:
  completions: 2
  parallelism: 2
  template:
    spec:
      containers:
        - name: mathsapp
          image: ubuntu
          command: ["expr",'3','+','5']
      restartPolicy: Never