apiVersion: v1
kind: Pod
metadata:
  name: myimg

spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
    - name: mypod
      image: wilsonshamim/echo-image
      env:
        - name: NAME
          value: VAL
      args: ["$(NAME)"]
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "SYS_TIME"]
      readinessProbe:
        exec:
          command:
            - cat
            - /app/is_ready
