apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
  labels:
    app: myrc-app

spec:
  template:
    metadata:
      name: mypod
      labels:
        app: front-end
    spec:
      containers:
      - name: mynginx
        image: nginx
  replicas: 3